apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: hieubui1312/auth
          env:
            - name: MONGO_URI
              value: "mongodb://auth-mongo-srv/auth"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: ports
      protocol: TCP
      port: 3000
      targetPort: 3000

#  kubectl create secret generic jwt-secret --from-literal=JWT_SECRET=HelloWorld
